export const dynamic = 'force-dynamic'
import type { Metadata } from 'next'
import './globals.css'
import './theme.css'
import { Toaster } from '@/components/ui/toaster'
import { ThemeProvider } from '@/lib/context/ThemeContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html >
      <body>
      <ThemeProvider>
     {children}
        <Toaster />
      </ThemeProvider>
      </body>
    </html>
  )
}
