export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import "./globals.css";
import "./theme.css";
import { Toaster } from "@/components/ui/toaster";

import Navigation from "@/components/Navigation";
import { ThemeProvider } from "@/lib/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="Green-dark">
      <head>
        <title>PDFigma</title>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
